version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:

  BeforeInstall:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: ec2-user

    - location: scripts/cleanup_old_files.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/verify_container.sh
      timeout: 300
      runas: ec2-user
